apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      service: nodejs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nodejs
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: nodejs
        image: subhash403/nodejs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
         requests:
           memory: "64Mi"
           cpu: "50m"
         limits:
           memory: "128Mi"
           cpu: "50m"


