 apiVersion: v1
 kind: Service
 metadata:
   name: nodejs
   namespace: default
   labels:
     app: nodejs
 spec:
   type: LoadBalancer
   ports:
   - port: 3000
     protocol: TCP
     name: http
   selector:
     service: nodejs
